services:
  api:
    build: ./backend       
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 
    network_mode: host
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    network_mode: host