# Generated by Django 5.1.3 on 2024-11-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=16, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=16, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('falla_reportada', models.TextField()),
                ('reparacion_efectuada', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olimpo.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olimpo.tecnico')),
            ],
        ),
    ]
