# Generated by Django 4.2.16 on 2024-12-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0002_dispositivoservicio_alter_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='status',
        ),
    ]
