# Generated by Django 5.1.3 on 2024-11-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0002_dispositivo_servicio_dispositivo_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='imeis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispositivos', to='olimpo.tipodispositivo'),
        ),
        migrations.DeleteModel(
            name='Imei',
        ),
    ]
