# Generated by Django 4.2.16 on 2024-12-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0003_remove_dispositivo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivoservicio',
            name='reparaciones',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='dispositivos',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='reparacion_efectuada',
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olimpo.dispositivoservicio')),
            ],
        ),
    ]
