# Generated by Django 4.2.16 on 2024-11-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0003_tipodispositivo_dispositivo_imeis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dispositivos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='olimpo.dispositivo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
