# Generated by Django 4.2.16 on 2024-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0004_remove_dispositivoservicio_reparaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoservicio',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
