# Generated by Django 4.2.16 on 2024-12-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0010_remove_dispositivo_imei1_remove_dispositivo_imei2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='olimpo.tipodispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivoservicio',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olimpo.dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivoservicio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olimpo.servicio'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpo.dispositivoservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpo.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
