# Generated by Django 4.2.16 on 2024-12-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpo', '0012_marca_remove_dispositivo_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='olimpo.modelo'),
        ),
    ]
